# Generated by Django 4.2.14 on 2024-10-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CVorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dof', models.DateField()),
                ('address', models.TextField()),
                ('likndein', models.URLField(blank=True, null=True)),
                ('skill', models.CharField(max_length=255)),
                ('langugaes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sendmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_no', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('budget', models.IntegerField()),
                ('desc', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cvorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.cvorders')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=20, null=True)),
                ('contracttype', models.CharField(choices=[('full', 'دوام كامل'), ('part', 'دوام جزئي'), ('remot', 'عمل عن بعد')], max_length=10, null=True)),
                ('jobtype', models.CharField(choices=[('spec', 'جهة خاصة'), ('gover', 'جهة حكومية')], max_length=10)),
                ('location', models.CharField(choices=[('abudhabi', 'أبوظبي'), ('dubai', 'دبي'), ('sharjah', 'الشارقة'), ('fujairah', 'الفحيرة'), ('rak', 'راس الخيمة'), ('ajman', 'عجمان')], max_length=10)),
                ('desc', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('applying', models.CharField(max_length=50, null=True)),
                ('applying_email', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=30)),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emailcat')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('A', 'لا يوجد'), ('B', 'ثانوي'), ('C', 'جامعي')], max_length=255)),
                ('education_name', models.CharField(max_length=255)),
                ('end_edu_date', models.DateField(blank=True, null=True)),
                ('cvorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.cvorders')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('date_commented', models.DateTimeField(auto_now_add=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='core.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=255)),
                ('cvorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.cvorders')),
            ],
        ),
    ]
