# Generated by Django 4.2.14 on 2024-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvorders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cvorders',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cvorders',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvorders',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cvorders',
            name='skill',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
